2024-10-15 10:14:34,132 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 10:14:34,148 - INFO - geting all the data
2024-10-15 10:14:34,148 - INFO - geting all the data
2024-10-15 10:17:00,441 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 10:17:00,448 - INFO - geting all the data
2024-10-15 10:17:00,448 - INFO - geting all the data
2024-10-15 10:17:27,512 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 10:17:27,519 - INFO - Getting the data by unique id
2024-10-15 10:17:27,519 - INFO - Getting the data by unique id
2024-10-15 10:17:27,524 - ERROR - error occured while geting the data by unique id
2024-10-15 10:17:27,524 - ERROR - error occured while geting the data by unique id
2024-10-15 10:17:42,208 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 10:17:42,214 - INFO - Getting the data by unique id
2024-10-15 10:17:42,214 - INFO - Getting the data by unique id
2024-10-15 10:17:42,216 - ERROR - error occured while geting the data by unique id
2024-10-15 10:17:42,216 - ERROR - error occured while geting the data by unique id
2024-10-15 10:17:44,816 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 10:17:44,816 - INFO - geting all the data
2024-10-15 10:17:44,816 - INFO - geting all the data
2024-10-15 11:05:03,279 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:05:03,283 - INFO - geting all the data
2024-10-15 11:05:03,283 - INFO - geting all the data
2024-10-15 11:12:13,750 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:12:13,756 - INFO - geting all the data
2024-10-15 11:12:13,756 - INFO - geting all the data
2024-10-15 11:15:37,858 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:15:37,866 - INFO - geting all the data
2024-10-15 11:15:37,866 - INFO - geting all the data
2024-10-15 11:15:39,077 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:15:39,079 - INFO - geting all the data
2024-10-15 11:15:39,079 - INFO - geting all the data
2024-10-15 11:17:05,077 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:17:05,081 - INFO - geting all the data
2024-10-15 11:17:05,081 - INFO - geting all the data
2024-10-15 11:17:05,668 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:17:05,668 - INFO - geting all the data
2024-10-15 11:17:05,668 - INFO - geting all the data
2024-10-15 11:17:06,071 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:17:06,071 - INFO - geting all the data
2024-10-15 11:17:06,071 - INFO - geting all the data
2024-10-15 11:17:06,400 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:17:06,400 - INFO - geting all the data
2024-10-15 11:17:06,400 - INFO - geting all the data
2024-10-15 11:17:06,567 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:17:06,567 - INFO - geting all the data
2024-10-15 11:17:06,567 - INFO - geting all the data
2024-10-15 11:19:21,637 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:21,649 - INFO - geting all the data
2024-10-15 11:19:21,649 - INFO - geting all the data
2024-10-15 11:19:22,527 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:22,530 - INFO - geting all the data
2024-10-15 11:19:22,530 - INFO - geting all the data
2024-10-15 11:19:22,913 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:22,913 - INFO - geting all the data
2024-10-15 11:19:22,913 - INFO - geting all the data
2024-10-15 11:19:23,027 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:23,027 - INFO - geting all the data
2024-10-15 11:19:23,027 - INFO - geting all the data
2024-10-15 11:19:23,561 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:23,561 - INFO - geting all the data
2024-10-15 11:19:23,561 - INFO - geting all the data
2024-10-15 11:19:27,748 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:27,755 - INFO - Getting the data by unique id
2024-10-15 11:19:27,755 - INFO - Getting the data by unique id
2024-10-15 11:19:27,755 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:27,755 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:32,057 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:32,059 - INFO - Getting the data by unique id
2024-10-15 11:19:32,059 - INFO - Getting the data by unique id
2024-10-15 11:19:32,059 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:32,059 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:32,648 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:32,651 - INFO - Getting the data by unique id
2024-10-15 11:19:32,651 - INFO - Getting the data by unique id
2024-10-15 11:19:32,651 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:32,651 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:32,860 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:19:32,863 - INFO - Getting the data by unique id
2024-10-15 11:19:32,863 - INFO - Getting the data by unique id
2024-10-15 11:19:32,864 - ERROR - error occured while geting the data by unique id
2024-10-15 11:19:32,864 - ERROR - error occured while geting the data by unique id
2024-10-15 11:20:11,008 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:20:11,011 - INFO - Getting the data by unique id
2024-10-15 11:20:11,011 - INFO - Getting the data by unique id
2024-10-15 11:20:11,011 - ERROR - error occured while geting the data by unique id
2024-10-15 11:20:11,011 - ERROR - error occured while geting the data by unique id
2024-10-15 11:20:13,646 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:20:13,652 - INFO - Getting the data by unique id
2024-10-15 11:20:13,652 - INFO - Getting the data by unique id
2024-10-15 11:20:13,653 - ERROR - error occured while geting the data by unique id
2024-10-15 11:20:13,653 - ERROR - error occured while geting the data by unique id
2024-10-15 11:21:07,652 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:21:07,653 - INFO - Getting the data by unique id
2024-10-15 11:21:07,653 - INFO - Getting the data by unique id
2024-10-15 11:21:07,654 - ERROR - error occured while geting the data by unique id
2024-10-15 11:21:07,654 - ERROR - error occured while geting the data by unique id
2024-10-15 11:21:39,412 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:21:39,412 - INFO - Getting the data by unique id
2024-10-15 11:21:39,412 - INFO - Getting the data by unique id
2024-10-15 11:21:39,416 - ERROR - error occured while geting the data by unique id
2024-10-15 11:21:39,416 - ERROR - error occured while geting the data by unique id
2024-10-15 11:22:13,483 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:22:18,748 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:22:18,748 - INFO - Getting the data by unique id
2024-10-15 11:22:18,748 - INFO - Getting the data by unique id
2024-10-15 11:22:18,752 - ERROR - error occured while geting the data by unique id
2024-10-15 11:22:18,752 - ERROR - error occured while geting the data by unique id
2024-10-15 11:22:25,735 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:22:25,735 - INFO - Getting the data by unique id
2024-10-15 11:22:25,735 - INFO - Getting the data by unique id
2024-10-15 11:22:25,735 - ERROR - error occured while geting the data by unique id
2024-10-15 11:22:25,735 - ERROR - error occured while geting the data by unique id
2024-10-15 11:24:08,338 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:08,344 - INFO - Getting the data by unique id
2024-10-15 11:24:08,344 - INFO - Getting the data by unique id
2024-10-15 11:24:16,225 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:16,232 - INFO - Getting the data by unique id
2024-10-15 11:24:16,232 - INFO - Getting the data by unique id
2024-10-15 11:24:29,617 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:29,617 - INFO - Getting the data by unique id
2024-10-15 11:24:29,617 - INFO - Getting the data by unique id
2024-10-15 11:24:31,688 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:31,689 - INFO - Getting the data by unique id
2024-10-15 11:24:31,689 - INFO - Getting the data by unique id
2024-10-15 11:24:33,667 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:33,667 - INFO - Getting the data by unique id
2024-10-15 11:24:33,667 - INFO - Getting the data by unique id
2024-10-15 11:24:36,758 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:36,765 - INFO - Getting the data by unique id
2024-10-15 11:24:36,765 - INFO - Getting the data by unique id
2024-10-15 11:24:39,765 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:24:39,765 - INFO - Getting the data by unique id
2024-10-15 11:24:39,765 - INFO - Getting the data by unique id
2024-10-15 11:26:21,478 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 11:26:21,485 - INFO - Getting the data by unique id
2024-10-15 11:26:21,485 - INFO - Getting the data by unique id
2024-10-15 11:26:21,495 - INFO - Updating the data by unique id
2024-10-15 11:26:21,495 - INFO - Updating the data by unique id
2024-10-15 11:26:21,526 - ERROR - An error occurred while updating data: (psycopg2.errors.NotNullViolation) null value in column "filename" of relation "detected_data" violates not-null constraint
DETAIL:  Failing row contains (4, null, null, null, null, null, null, null).

[SQL: UPDATE detected_data SET filename=%(filename)s, class_id=%(class_id)s, x_center=%(x_center)s, y_center=%(y_center)s, width=%(width)s, height=%(height)s, confidence=%(confidence)s WHERE detected_data.id = %(detected_data_id)s]
[parameters: {'filename': None, 'class_id': None, 'x_center': None, 'y_center': None, 'width': None, 'height': None, 'confidence': None, 'detected_data_id': 4}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-10-15 11:26:21,526 - ERROR - An error occurred while updating data: (psycopg2.errors.NotNullViolation) null value in column "filename" of relation "detected_data" violates not-null constraint
DETAIL:  Failing row contains (4, null, null, null, null, null, null, null).

[SQL: UPDATE detected_data SET filename=%(filename)s, class_id=%(class_id)s, x_center=%(x_center)s, y_center=%(y_center)s, width=%(width)s, height=%(height)s, confidence=%(confidence)s WHERE detected_data.id = %(detected_data_id)s]
[parameters: {'filename': None, 'class_id': None, 'x_center': None, 'y_center': None, 'width': None, 'height': None, 'confidence': None, 'detected_data_id': 4}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-10-15 12:08:31,686 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 12:08:31,716 - INFO - geting all the data
2024-10-15 12:08:31,716 - INFO - geting all the data
2024-10-15 12:08:35,648 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 12:08:35,648 - INFO - geting all the data
2024-10-15 12:08:35,648 - INFO - geting all the data
2024-10-15 12:08:59,251 - INFO - Configuring the datbase connection using SQLAlchemy
2024-10-15 12:08:59,256 - INFO - geting all the data
2024-10-15 12:08:59,256 - INFO - geting all the data
